#!/usr/bin/env python3
r"""
build_registry.py — populate the template library from the shipped CEC
SingleFamilyPrototypes.

Copies each 2025_CZ##_####ft2_Prop.ribd25 into reference_files/ and writes
templates/registry.json with one entry per prototype, reading each file's real
ClimateZone string + story count. Hand-curated non-CEC entries (e.g. the Alaniz
loop-test template) are preserved.

    python build_registry.py                 # auto-detect CBECC Projects
    python build_registry.py --src "<path to SingleFamilyPrototypes>"
    python build_registry.py --dry-run       # show what it would do

area_targets are left empty by default (project-level patching only). To let a
template's conditioned floor area be overridden, fill area_targets for that
entry by hand (see templates/README.md). Stdlib only.
"""

import argparse
import json
import os
import re
import shutil

HERE = os.path.dirname(os.path.abspath(__file__))
REF = os.path.join(HERE, "reference_files")
REGISTRY = os.path.join(HERE, "templates", "registry.json")

FNAME_RE = re.compile(r"^2025_CZ(\d{1,2})_(\d+)ft2_Prop\.ribd25$", re.IGNORECASE)

# The Alaniz loop-test entry is kept regardless of the CEC scan.
ALANIZ = {
    "id": "alaniz_adu",
    "label": "Alaniz ADU (CZ13, 437 ft2, slab) - loop test only",
    "path": "reference_files/Alaniz_residence.ribd25",
    "code_cycle": "2025",
    "tags": {"climate_zone": 13, "stories": 1, "foundation": "slab",
             "size_ft2": 437, "has_adu": True},
    "area_targets": [
        {"type": "Zone", "name": "ADU", "prop": "FloorArea"},
        {"type": "SlabFloor", "name": "Slab On Grade 1", "prop": "Area"},
    ],
    "notes": "Minimal file (no HVAC/DHW/windows/roof). Loop testing only, not production.",
}


def autodetect_src():
    base = os.path.join(os.path.expanduser("~"), "OneDrive", "Documents",
                        "CBECC 2025 Projects", "SingleFamilyPrototypes")
    alt = os.path.join(os.path.expanduser("~"), "Documents",
                       "CBECC 2025 Projects", "SingleFamilyPrototypes")
    return base if os.path.isdir(base) else alt


def read_climate_and_stories(path):
    cz_string, stories = None, None
    with open(path, "r", encoding="utf-8", errors="replace") as fh:
        for line in fh:
            s = line.strip()
            if cz_string is None and s.startswith("ClimateZone ="):
                m = re.search(r'"([^"]+)"', s)
                if m:
                    cz_string = m.group(1)
            if s.startswith("NumStories ="):
                try:
                    n = int(float(s.split("=", 1)[1].strip()))
                    stories = max(stories or 0, n)
                except ValueError:
                    pass
    return cz_string, stories


def build(src, dry_run=False):
    if not os.path.isdir(src):
        raise SystemExit(f"prototypes folder not found: {src}")
    os.makedirs(REF, exist_ok=True)

    entries = [ALANIZ]
    files = sorted(f for f in os.listdir(src) if FNAME_RE.match(f))
    for fn in files:
        m = FNAME_RE.match(fn)
        cz, size = int(m.group(1)), int(m.group(2))
        src_path = os.path.join(src, fn)
        cz_string, stories = read_climate_and_stories(src_path)
        city = ""
        if cz_string:
            cm = re.search(r"\(([^)]+)\)", cz_string)
            city = cm.group(1) if cm else ""

        dst_rel = f"reference_files/{fn}"
        if not dry_run:
            shutil.copy2(src_path, os.path.join(HERE, dst_rel))

        entries.append({
            "id": f"cec_cz{cz}_{size}",
            "label": f"CEC prototype - CZ{cz} {city}, {size} ft2 (Proposed)",
            "path": dst_rel,
            "code_cycle": "2025",
            "tags": {"climate_zone": cz, "stories": stories,
                     "foundation": "slab", "size_ft2": size},
            "area_targets": [],
            "notes": f"Shipped CEC prototype ({fn}). Fill area_targets to allow "
                     f"floor-area override.",
        })

    registry = {
        "$comment": "Auto-generated by build_registry.py from the CEC "
                    "SingleFamilyPrototypes, plus hand-curated entries. "
                    "Template .ribd25 files live in reference_files/ (git-ignored).",
        "templates": entries,
    }
    if dry_run:
        print(json.dumps(registry, indent=2))
        print(f"\n[dry-run] {len(files)} CEC prototype(s) would be copied to reference_files/")
        return
    with open(REGISTRY, "w", encoding="utf-8") as fh:
        json.dump(registry, fh, indent=2)
        fh.write("\n")
    print(f"copied {len(files)} CEC prototype(s) -> reference_files/")
    print(f"wrote {REGISTRY} with {len(entries)} template(s)")


def main():
    ap = argparse.ArgumentParser(description="Build the template registry from CEC prototypes.")
    ap.add_argument("--src", default=autodetect_src())
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    build(args.src, dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
